import { WorkGallery } from '@/components/WorkGallery';
import { featuredLocations } from '@/data/navigation';
import Image from 'next/image';
import Link from 'next/link';
import { ContactButtons } from '@/components/cta/ContactButtons';
import { Icon } from '@/components/Icon';
import { Services, Steps, Regions, WhyUs, CTABand, FAQSection } from '@/components/Sections';
import { pageMetadata } from '@/lib/metadata';
import { LocationDirectory } from '@/components/LocationDirectory';
export const metadata = pageMetadata('En Yakın Lastikçi | Yerinde Mobil Lastik Servisi', 'İstanbul, Sakarya, Sapanca, Kocaeli ve Düzce’de 7/24 mobil lastik desteği. Telefonla ulaşın veya WhatsApp’tan konum gönderin, hizmet uygunluğunu birlikte netleştirelim.');
export default function Home(){return <main id="main"><section className="hero"><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow"><span className="eyebrow-line"/> SİZ NEREDEYSENİZ, DESTEK ORADA</p><h1>Size en yakın<br/><span>mobil lastikçi.</span></h1><p className="hero-description">Lastik sorununuz yolunuzu kesmesin. İstanbul, Sakarya, Kocaeli ve Düzce’de bulunan ekiplerimizle konumunuza mobil lastik desteği. Tüm araçlara, dört ilin tüm ilçelerinde 7/24 hizmet.</p><ContactButtons placement="hero"/><div className="hero-assurances"><span><Icon name="check"/> 7/24 mobil destek</span><span><Icon name="check"/> Yerinde hizmet</span></div><a className="hero-how" href="#nasil-calisir">Nasıl çalışıyor? <span>↓</span></a></div><div className="hero-visual"><Image src="/images/mobil-lastik-servisi.webp" alt="Yol kenarında araç tekerleği üzerinde çalışan eldivenli eller; temsili servis görseli" fill sizes="(max-width: 800px) 100vw, 50vw" preload className="hero-image"/><div className="photo-caption"><span className="photo-icon"><Icon name="pin"/></span><div><strong>Servise giden siz olmayın.</strong><span>Mobil lastik desteği konumunuza gelsin.</span></div></div><span className="image-index">MOBİL LASTİK SERVİSİ / 01</span></div></div></section><div className="coverage-strip"><div className="container"><span><Icon name="pin"/> HİZMET BÖLGELERİMİZ</span>{featuredLocations.map(({slug:p,name:n})=><Link key={p} href={`/${p}`}>{n}<span>↗</span></Link>)}</div></div><Services/><WorkGallery/><Steps/><Regions/><WhyUs/><CTABand/><section className="section section-soft"><div className="container"><p className="eyebrow">ŞEHİRDEN İLÇEYE</p><h2>Hizmet bölgenizi inceleyin.</h2><LocationDirectory compact/></div></section><FAQSection/><CTABand final/></main>;}

