import Link from 'next/link';
import type { Location, Service } from '@/types/content';
import { BreadcrumbSchema, JsonLd } from './seo/JsonLd';
import { ContactButtons } from './cta/ContactButtons';
import { Services, Steps, FAQSection, CTABand } from './Sections';
import { LocationDirectory } from './LocationDirectory';
import { LocationPageView } from './Analytics';
import { cities, visibleLocations } from '@/data/locations';
import { canonicalOrigin, siteConfig } from '@/siteConfig';
export function Breadcrumb({items}:{items:{name:string;path:string}[]}){return <><nav className="breadcrumb" aria-label="İçerik yolu">{items.map((x,i)=><span key={x.path}>{i>0&&<span aria-hidden="true"> / </span>}{i===items.length-1?<span aria-current="page">{x.name}</span>:<Link href={x.path}>{x.name}</Link>}</span>)}</nav><BreadcrumbSchema items={items}/></>;}
export function PageHero({title,intro,path,children,crumbs}:{title:string;intro:string;path:string;children?:React.ReactNode;crumbs?:{name:string;path:string}[]}){return <section className="inner-hero"><div className="container"><Breadcrumb items={crumbs||[{name:'Ana sayfa',path:'/'},{name:title,path}]}/><p className="eyebrow">KONUMUNUZA MOBİL DESTEK</p><h1>{title}</h1><p className="intro">{intro}</p>{children}</div></section>;}
export function LocationPage({location:l}:{location:Location}){const name=l.district==='Merkez'?`${l.city} Merkez`:l.district||l.city;const parent=cities.find(c=>c.city===l.city);const crumbs=[{name:'Ana sayfa',path:'/'},...(l.district&&parent?[{name:l.city,path:`/${parent.slug}`}]:[]),{name:`${name} mobil lastikçi`,path:`/${l.slug}`}];const nearby=visibleLocations.filter(x=>l.nearbyDistricts.includes(x.slug));return <main id="main"><LocationPageView slug={l.slug}/><PageHero title={`${name} mobil lastikçi`} intro={l.intro} path={`/${l.slug}`} crumbs={crumbs}>{!l.confirmed&&<p className="draft-note">Örnek ilçe içeriği. Bu bölgede hizmet kapsamı henüz doğrulanmadı.</p>}<ContactButtons placement={`location_${l.slug}`}/><p className="dispatch-note">{siteConfig.dispatchNotice}</p></PageHero><section className="section"><div className="container reading-grid"><div className="prose"><h2>{name} için yerinde lastik desteği</h2><p>{l.description}</p>{l.advice.map(a=><div key={a.title}><h2>{a.title}</h2><p>{a.text}</p></div>)}{l.serviceAreas.length>0&&<><h2>Hizmet verilen alanlar</h2><ul>{l.serviceAreas.map(a=><li key={a}>{a}</li>)}</ul></>}<h2>İletişime geçmeden önce</h2><p>Konumunuzu, araç modelinizi, lastik ebatını ve sorunun kısa açıklamasını hazırlayın. WhatsApp görüşmesinde konum paylaşımını sizin başlatmanız gerekir. Site otomatik konum toplamaz.</p></div><aside className="info-card"><h2>Doğru yönlendirme için</h2><p>Konumunuz + araç bilgisi + lastik sorunu.</p><ContactButtons placement="location_sidebar"/><p className="small" style={{marginTop:20}}>Hizmet uygunluğu, ücret ve tahmini süre görüşmede netleşir. Belirtilen yerler hizmet bölgesidir; fiziksel şube değildir.</p></aside></div></section><Services/><Steps/>{!l.district&&<section className="section"><div className="container"><p className="eyebrow">BÖLGENİZİ İNCELEYİN</p><h2>{l.city} hizmet bölgeleri</h2><LocationDirectory city={l.city}/></div></section>}{nearby.length>0&&<section className="section"><div className="container"><h2>İlgili ilçe sayfaları</h2><div className="link-list">{nearby.map(n=><Link href={`/${n.slug}`} key={n.slug}>{n.district==='Merkez'?`${n.city} Merkez`:n.district||n.city}</Link>)}</div></div></section>}<FAQSection items={l.faq}/><CTABand final/></main>;}
export function ServicePage({service:s}:{service:Service}){return <main id="main"><PageHero title={s.name} intro={s.description} path={`/${s.slug}`}>{!s.confirmed&&<p className="draft-note">Örnek hizmet içeriği. Hizmetin işletme tarafından sunulduğu henüz doğrulanmadı.</p>}<ContactButtons placement={`service_${s.slug}`}/></PageHero><section className="section"><div className="container reading-grid"><div className="prose"><h2>Nasıl destek alabilirsiniz?</h2><ol>{s.steps.map(x=><li key={x}>{x}</li>)}</ol><h2>Yönlendirmeden önce bilgi alın</h2><p>Uygulanacak işlem, gerekli malzeme ve konum ücretlendirmeyi etkileyebilir. Ekip yönlendirilmeden önce hizmet uygunluğunu ve ücret bilgisini öğrenin. Kesin varış süresi veya her lastik için onarım garantisi verilmez.</p></div><aside className="info-card"><h2>Hizmet bölgeleri</h2><div className="link-list">{cities.map(c=><Link key={c.slug} href={`/${c.slug}`}>{c.city}</Link>)}<Link href="/sakarya/sapanca">Sapanca</Link></div></aside></div></section><FAQSection items={s.faq}/><CTABand final/>{s.confirmed&&<JsonLd data={{'@context':'https://schema.org','@type':'Service',name:s.name,description:s.description,url:`${canonicalOrigin}/${s.slug}`,provider:{'@id':`${canonicalOrigin}/#business`},areaServed:cities.map(c=>({'@type':'AdministrativeArea',name:c.city}))}}/>}</main>;}
