import { featuredLocations } from '@/data/navigation';
import Link from 'next/link';
import { visibleServices } from '@/data/services';
import { commonFaq } from '@/data/faq';
import type { FAQ } from '@/types/content';
import { Icon } from './Icon';
import { ContactButtons } from './cta/ContactButtons';
export function Services(){return <section className="section" id="hizmetler"><div className="container"><div className="section-heading"><div><p className="eyebrow">YERİNDE LASTİK DESTEĞİ</p><h2>Bir sorun. Doğru çözüm.</h2></div><p>İhtiyacınızı anlatın.<br/>Size uygun müdahaleyi birlikte belirleyelim.</p></div><div className="service-grid">{visibleServices.map((s,i)=><Link className="service-card" href={`/${s.slug}`} key={s.slug}><div className="service-top"><Icon name={s.icon}/><span>0{i+1}</span></div><h3>{s.name}</h3>{!s.confirmed&&<span className="service-draft">Örnek hizmet · teyit bekliyor</span>}<p>{s.short}</p><span className="text-link">Hizmeti incele <Icon name="arrow"/></span></Link>)}</div></div></section>;}
export function Steps(){return <section className="section section-soft" id="nasil-calisir"><div className="container"><p className="eyebrow">ÜÇ ADIMDA MOBİL DESTEK</p><h2>Konumunuzu paylaşın.<br/>Gerisini birlikte planlayalım.</h2><div className="steps">{[['01','Bize ulaşın','Arayın veya WhatsApp’tan konumunuzu ve lastik sorununuzu paylaşın.'],['02','Hizmeti netleştirelim','Konuma erişimi, ekip uygunluğunu ve ücret bilgisini görüşelim.'],['03','Yerinde destek alın','Uygun ekip yönlendirilsin, lastiğiniz için gerekli müdahale yapılsın.']].map(([n,t,d])=><article key={n}><span className="step-number">{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div><p className="small">Varış süresi; konum, trafik ve ekip durumuna göre görüşme sırasında paylaşılır.</p></div></section>;}
export function Regions(){return <section className="section" id="bolgeler"><div className="container"><div className="section-heading"><div><p className="eyebrow">YAKININIZDAKİ DESTEĞİ BULUN</p><h2>Yolunuz nereye düşerse.</h2></div><Link className="text-link" href="/hizmet-bolgeleri">Tüm hizmet bölgeleri <Icon name="arrow"/></Link></div><div className="region-grid">{featuredLocations.map(({slug:s,name:n,description:d,highlight})=><Link className={`region-card ${highlight?'region-highlight':''}`} href={`/${s}`} key={s}><Icon name="pin"/><h3>{n}</h3><p>{d}</p><Icon name="arrow"/></Link>)}</div><p className="small region-note">Hizmet bölgeleri fiziksel şube değildir. Dört ilin tüm ilçelerinde hizmet veriyoruz; tam konuma erişim ve ekip uygunluğu görüşmede netleşir.</p></div></section>;}
export function WhyUs(){return <section className="section section-dark"><div className="container why-grid"><div><p className="eyebrow">İŞİNİZİ KOLAYLAŞTIRAN HİZMET</p><h2>Yolda sorun var.<br/>İletişimde olmasın.</h2><p>İhtiyacınızı doğrudan anlatın, seçeneklerinizi öğrenin.<br/>Sürpriz vaatler yerine açık iletişim.</p></div><div className="benefits">{[['Mobil hizmet','Aracın bulunduğu konuma göre çözüm.'],['Kolay iletişim','Telefon ya da WhatsApp: seçim sizin.'],['Konumla yönlendirme','Adres tarifini kolaylaştıran konum paylaşımı.'],['İşlem öncesi bilgi','Hizmet uygunluğunu ve ücreti önce görüşün.']].map(([t,d])=><div key={t}><Icon name="check"/><div><h3>{t}</h3><p>{d}</p></div></div>)}</div></div></section>;}
export function CTABand({final=false}:{final?:boolean}){return <section className={final?'section final-cta':'section'}><div className={`container ${final?'':'cta-band'}`}><div><p className="eyebrow">BİR GÖRÜŞMEYLE BAŞLAYALIM</p><h2>{final?'Yolda kalmayın. Bize ulaşın.':'Lastik sorunu planınızı değiştirmesin.'}</h2><p>Konumunuzu paylaşın, uygun hizmeti birlikte netleştirelim.</p></div><ContactButtons placement={final?'final':'midpage'}/></div></section>;}
export function FAQSection({items=commonFaq}:{items?:FAQ[]}){return <section className="section"><div className="container faq-grid"><div><p className="eyebrow">AKLINIZDA SORU KALMASIN</p><h2>Sık sorulan<br/>sorular.</h2><p>Yardım çağırmadan önce<br/>bilmek istedikleriniz.</p></div><div>{items.map(f=><details className="faq-item" key={f.question}><summary>{f.question}<span aria-hidden="true">+</span></summary><p>{f.answer}</p></details>)}</div></div></section>;}
