import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createLoader} from './lib/load-ts.mjs';
const passed=[];const check=(name,fn)=>{fn();passed.push(name);};const plain=x=>JSON.parse(JSON.stringify(x));
const store=()=>{const values=new Map();return {getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)};};
const fixture=(verified,env={})=>createLoader({env,transformSource:(f,s)=>f.endsWith('siteConfig.ts')&&verified?s.replace('businessVerified: false','businessVerified: true'):s});
check('Noindex preview uses production canonical, empty sitemap and permissive robots',()=>{const load=fixture(false);assert.equal(load('siteConfig.ts').isIndexable,false);assert.equal(load('lib/metadata.ts').pageMetadata('x','x','/sakarya/sapanca').alternates.canonical,'https://lastikcienyakin.com/sakarya/sapanca');assert.equal(load('app/sitemap.ts').default().length,0);assert.equal(load('app/robots.ts').default().rules.allow,'/');});
check('Index flag cannot bypass business verification',()=>assert.equal(fixture(false,{SITE_INDEXABLE:'true'})('siteConfig.ts').isIndexable,false));
check('Production fixture: 15 sitemap URLs and 74 editorial holds excluded',()=>{const load=fixture(true,{SITE_INDEXABLE:'true',INCLUDE_DRAFT_CONTENT:'true'});const {locations,visibleLocations}=load('data/locations.ts');assert.equal(visibleLocations.length,79);assert.equal(locations.filter(l=>l.indexReady).length,5);assert.equal(load('siteConfig.ts').includeDrafts,false);const urls=load('app/sitemap.ts').default().map(x=>x.url);assert.equal(urls.length,15);for(const l of locations){assert.equal(urls.includes(`https://lastikcienyakin.com/${l.slug}`),l.confirmed&&l.indexReady);assert.equal(load('lib/metadata.ts').pageMetadata(l.seoTitle,l.seoDescription,`/${l.slug}`,l.confirmed&&l.indexReady).robots.index,l.confirmed&&l.indexReady);}assert.equal(load('app/robots.ts').default().sitemap,'https://lastikcienyakin.com/sitemap.xml');});
check('Placeholder phone keeps indexing disabled',()=>assert.equal(fixture(true,{SITE_INDEXABLE:'true',NEXT_PUBLIC_BUSINESS_PHONE:'+900000000000'})('siteConfig.ts').isIndexable,false));
check('Default service visibility retains 75 districts and four confirmed services',()=>{const load=fixture(false);assert.equal(load('data/locations.ts').visibleLocations.filter(l=>l.district).length,75);assert.equal(load('data/services.ts').visibleServices.length,4);});
function harness(){const localStorage=store(),sessionStorage=store(),window={location:{pathname:'/sakarya/sapanca',search:'?utm_source=google&utm_medium=cpc&utm_campaign=sapanca&ignored=x'},dataLayer:[]};const api=createLoader({globals:{window,localStorage,sessionStorage}})('lib/analytics.ts');return {api,window,localStorage,sessionStorage};}
check('No consent means no events or attribution storage',()=>{const h=harness();h.api.configureTracking('gtm');h.api.track('phone_click');assert.equal(h.window.dataLayer.length,0);assert.equal(h.sessionStorage.getItem('campaign-attribution'),null);});
check('GTM mode sends only once even when gtag exists',()=>{const h=harness();h.localStorage.setItem('measurement-consent','granted');let calls=0;h.window.gtag=()=>calls++;h.api.configureTracking('gtm');h.api.track('phone_click');assert.equal(h.window.dataLayer.length,1);assert.equal(calls,0);});
check('Direct mode sends once and failed tag does not break CTA',()=>{const h=harness();h.localStorage.setItem('measurement-consent','granted');let calls=0;h.window.gtag=()=>calls++;h.api.configureTracking('gtag');h.api.track('whatsapp_click');assert.equal(calls,1);assert.equal(h.window.dataLayer.length,0);h.window.gtag=()=>{throw Error('tag unavailable');};assert.doesNotThrow(()=>h.api.track('phone_click'));});
check('Early location event flushes only once after initialization',()=>{const h=harness();h.localStorage.setItem('measurement-consent','granted');h.api.track('location_page_view');h.api.configureTracking('gtm');h.api.configureTracking('gtm');assert.equal(h.window.dataLayer.length,1);});
check('Late consent preserves pending event and disabled mode drops events',()=>{const h=harness();h.api.configureTracking('disabled');h.localStorage.setItem('measurement-consent','granted');h.api.prepareTracking();h.api.track('location_page_view');h.api.configureTracking('gtm');assert.equal(h.window.dataLayer.length,1);h.api.configureTracking('disabled');h.api.track('phone_click');assert.equal(h.window.dataLayer.length,1);});
check('UTM persists on navigation, excludes arbitrary fields and tolerates corrupt storage',()=>{const h=harness();h.localStorage.setItem('measurement-consent','granted');const first=plain(h.api.attribution());assert.equal(first.ignored,undefined);h.window.location.search='';assert.deepEqual(plain(h.api.attribution()),first);h.sessionStorage.setItem('campaign-attribution','null');assert.deepEqual(plain(h.api.attribution()),{});h.sessionStorage.setItem('campaign-attribution','broken');assert.deepEqual(plain(h.api.attribution()),{});});
check('Unavailable storage does not break tracking',()=>{const failing={getItem(){throw Error('blocked');}};const api=createLoader({globals:{localStorage:failing,sessionStorage:failing,window:{location:{}}}})('lib/analytics.ts');assert.doesNotThrow(()=>api.track('phone_click'));});
function component(ids,choice='granted'){
 const localStorage=store(),sessionStorage=store();localStorage.setItem('measurement-consent',choice);
 const scripts=[],refs=[];let cursor=0,effects=[];
 const window={dataLayer:[],location:{pathname:'/sakarya/sapanca',search:'?utm_source=google',href:'https://lastikcienyakin.com/sakarya/sapanca?utm_source=google'}};
 const document={title:'Sapanca',referrer:'https://www.google.com/',getElementById:id=>scripts.find(s=>s.id===id),createElement:()=>({}),head:{appendChild:s=>scripts.push(s)}};
 const react={useRef:initial=>{const i=cursor++;return refs[i]||(refs[i]={current:initial});},useEffect:fn=>effects.push(fn),useSyncExternalStore:(_subscribe,get)=>get()};
 const load=createLoader({globals:{window,document,localStorage,sessionStorage},modules:{react,'next/navigation':{usePathname:()=>window.location.pathname}}});
 return {window,scripts,api:load('lib/analytics.ts'),render(){cursor=0;effects=[];load('components/Analytics.tsx').Analytics(ids);effects.forEach(fn=>fn());}};
}
check('Analytics effect loads nothing without IDs or consent',()=>{for(const [ids,choice] of [[{gtmId:'',gaId:'',adsId:''},'granted'],[{gtmId:'GTM-TEST',gaId:'',adsId:''},'denied']]){const h=component(ids,choice);h.render();assert.equal(h.scripts.length,0);assert.equal(h.window.dataLayer.length,0);}});
check('Direct effect: consent before config, one script, one page view per route',()=>{const h=component({gtmId:'',gaId:'G-TEST',adsId:''});h.render();h.render();const cmds=()=>h.window.dataLayer.map(x=>Array.from(x));assert.equal(h.scripts.length,1);assert.equal(cmds()[0][0],'consent');assert.equal(cmds().find(x=>x[0]==='config')[2].send_page_view,false);assert.equal(cmds().filter(x=>x[1]==='page_view').length,1);h.window.location.pathname='/istanbul';h.window.location.href='https://lastikcienyakin.com/istanbul';h.render();assert.equal(cmds().filter(x=>x[1]==='page_view').length,2);});
check('GTM takes precedence over GA/Ads IDs and does not duplicate events',()=>{const h=component({gtmId:'GTM-TEST',gaId:'G-TEST',adsId:'AW-123'});h.render();h.render();assert.equal(h.scripts.length,1);assert(h.scripts[0].src.includes('/gtm.js?'));assert.equal(h.window.dataLayer.filter(x=>x.event==='virtual_page_view').length,1);h.api.track('phone_click');assert.equal(h.window.dataLayer.filter(x=>x.event==='phone_click').length,1);});
check('Business schema uses Organization without an address and honors config logo/email',()=>{const load=fixture(false),cfg=load('siteConfig.ts').siteConfig;cfg.businessHours=['Mo-Fr 09:00-17:00'];cfg.email='test@example.invalid';const graph=load('components/seo/JsonLd.tsx').BusinessSchema().props.data['@graph'];assert.equal(graph[0]['@type'],'Organization');assert.equal(graph[0].address,undefined);assert.equal(graph[0].openingHours,undefined);assert.equal(graph[0].logo,'https://lastikcienyakin.com/lastikcienyakinlogo.png');assert.equal(graph[0].email,'test@example.invalid');});
check('Local-business schema appears only in a verified address fixture',()=>{const load=fixture(true),cfg=load('siteConfig.ts').siteConfig;cfg.address={streetAddress:'TEST ONLY',addressLocality:'TEST ONLY',postalCode:'00000',addressCountry:'TR'};cfg.businessHours=['Mo-Fr 09:00-17:00'];const business=load('components/seo/JsonLd.tsx').BusinessSchema().props.data['@graph'][0];assert.equal(business['@type'],'TireShop');assert.equal(business.address['@type'],'PostalAddress');assert.equal(business.openingHours.length,1);});
check('JSON-LD escapes script terminators safely',()=>{const component=fixture(false)('components/seo/JsonLd.tsx').JsonLd({data:{name:'</script><script>bad</script>'}});const html=component.props.dangerouslySetInnerHTML.__html;assert(!html.includes('<'));assert.equal(JSON.parse(html).name,'</script><script>bad</script>');});
fs.writeFileSync('LOGIC-AUDIT.json',JSON.stringify({checkedAt:new Date().toISOString(),tests:passed.length,passed,errors:[],note:'In-memory verified fixture; real configuration remains unverified. Analytics runs with inert DOM/hooks, without external requests.'},null,2));console.log(`${passed.length} logic checks PASS`);
